import { describe, expect, it, vi } from "vitest";
import { buildPlannerWorkspaceBundleParamsFromBundles } from "./buildPlannerWorkspaceBundleParamsFromBundles";
import type { usePlannerPageState } from "./usePlannerPageState";

type PlannerState = ReturnType<typeof usePlannerPageState>;

describe("buildPlannerWorkspaceBundleParamsFromBundles", () => {
  it("maps bundle sources into workspace bundle params", () => {
    const plannerState = {
      profileName: "FCO",
      selectedNodeId: "node-1",
      isMobileLayout: true,
      mobileToolbarOpen: false,
      rootNodeId: "root-1",
      setRfInstance: vi.fn(),
      activePortalRefId: "ref-1",
      setActivePortalRefId: vi.fn(),
      setSelectedNodeId: vi.fn(),
      setMobileQuickEditorMode: vi.fn(),
      scheduleHoverUpdate: vi.fn(),
      hoveredEdgeId: null,
      hoveredNodeId: null,
      isDraggingRef: { current: false },
      setPortalContextMenu: vi.fn(),
      portalContextMenu: null,
      setContextMenu: vi.fn(),
      contextMenu: null,
      busyAction: false,
      paletteOpen: false,
      paletteQuery: "",
      paletteIndex: 0,
      paletteInputRef: { current: null },
      setPaletteQuery: vi.fn(),
      setPaletteIndex: vi.fn(),
      setMobileSidebarOpen: vi.fn(),
      setMobileToolbarOpen: vi.fn(),
      setMobileQuickBubbleOpen: vi.fn(),
      setMobileQuickEditorOpen: vi.fn(),
      setPaletteOpen: vi.fn(),
      mobileSidebarOpen: false,
      mobileQuickEditorOpen: false,
      mobileQuickBubbleOpen: false,
      mobileQuickEditorMode: "compact",
      renameTitle: "Rename",
      newRefLabel: "Bubble",
      bodyDraft: "",
      newRefCode: "",
      newRefColor: "#40B6FF",
      mobileQuickBubbleInputRef: { current: null },
      mobileQuickBubbleEditName: "",
      setCurrentRootId: vi.fn(),
      setRenameTitle: vi.fn(),
      setNewRefLabel: vi.fn(),
      setBodyDraft: vi.fn(),
      setNewRefCode: vi.fn(),
      setNewRefColor: vi.fn(),
      setMobileSidebarSection: vi.fn(),
      setMobileQuickBubbleEditName: vi.fn(),
      error: null,
      currentRootId: "root-1",
      storyLaneMode: false,
      newChildTitle: "",
      setNewChildTitle: vi.fn(),
      setStoryLaneMode: vi.fn(),
      renameInputRef: { current: null },
      newStoryStepText: "",
      setNewStoryStepText: vi.fn(),
      refScopeFilter: "all",
      setRefScopeFilter: vi.fn(),
      refCategoryFilter: "all",
      setRefCategoryFilter: vi.fn(),
      refSearchQuery: "",
      setRefSearchQuery: vi.fn(),
      editRefId: null,
      editRefLabel: "",
      setEditRefLabel: vi.fn(),
      editRefCode: "",
      setEditRefCode: vi.fn(),
      editRefType: "entity",
      setEditRefType: vi.fn(),
      editRefTags: "",
      setEditRefTags: vi.fn(),
      editRefContact: "",
      setEditRefContact: vi.fn(),
      editRefNotes: "",
      setEditRefNotes: vi.fn(),
      editRefLinks: "",
      setEditRefLinks: vi.fn(),
      linkNodeQuery: "",
      setLinkNodeQuery: vi.fn(),
      linkTargetNodeId: null,
      setLinkTargetNodeId: vi.fn(),
      mergeFromRefId: null,
      setMergeFromRefId: vi.fn(),
      newRefLabelInputRef: { current: null },
      newRefType: "entity",
      setNewRefType: vi.fn(),
      searchInputRef: { current: null },
      searchQuery: "",
      setSearchQuery: vi.fn(),
      setSidebarCollapsed: vi.fn(),
    } as unknown as PlannerState;

    const canvasGraph = {
      reactFlowNodes: [],
      flowEdges: [],
      handleNodesChange: vi.fn(),
      toggleNodeCollapse: vi.fn(),
      filteredTreeIds: ["root-1", "node-1"],
      searchMatchingIds: new Set<string>(["node-1"]),
    };
    const derived = {
      selectedNodeRefs: [],
      canCreateBubbleFromInput: false,
      nextAutoBubbleCode: "B001",
      bubblePrefixSuggestions: [],
      selectedNodeChildren: [],
      selectedNodeCollapsed: false,
      effectiveNewBubbleCode: "B001",
      activePortalRef: null,
      saveSelectedBody: vi.fn(),
      currentRootPath: [],
      projectPages: [],
      activeProjectPageId: null,
      activeProjectPageIndex: 0,
      selectedNodeHasStoryChildren: false,
      activePortalTargets: [],
      newRefSuggestions: [],
      describeRefTargets: vi.fn(() => ""),
      filteredRefs: [],
      selectedNodeRefIds: new Set<string>(),
      describeRefLibraryPreview: vi.fn(() => ""),
      linkableNodeOptions: [],
      editableRefTargets: [],
      mergeCandidateRefs: [],
    } as never;
    const mutationHandleContextAddChild = vi.fn();
    const mutation = {
      selectRefForEditing: vi.fn(),
      onNodeDrag: vi.fn(),
      onNodeDragStop: vi.fn(),
      onSelectionDragStop: vi.fn(),
      handleContextAddChild: mutationHandleContextAddChild,
      handleContextAddStorySibling: vi.fn(),
      handleContextDelete: vi.fn(),
      handleContextDuplicate: vi.fn(),
      handleContextRename: vi.fn(),
      handleContextAddCrossRef: vi.fn(),
      handleContextChangeType: vi.fn(),
      handleContextToggleTaskStatus: vi.fn(),
      deletePortalByRefId: vi.fn(),
      renameSelected: vi.fn(),
      createCrossRef: vi.fn(),
      applyBubbleSuggestion: vi.fn(),
      setNodeTaskStatus: vi.fn(),
      createChild: vi.fn(),
      saveMobileQuickBubbleName: vi.fn(),
      updateCrossRefColor: vi.fn(),
      cleanUpCrossRefs: vi.fn(),
      setNodeColor: vi.fn(),
      deleteSelected: vi.fn(),
      toggleStoryStepDone: vi.fn(),
      moveStoryStep: vi.fn(),
      deleteStoryStep: vi.fn(),
      addStoryStep: vi.fn(),
      linkCrossRefToNode: vi.fn(),
      detachCrossRef: vi.fn(),
      saveCrossRefEdits: vi.fn(),
      duplicateCrossRef: vi.fn(),
      mergeCrossRefIntoEdited: vi.fn(),
      deleteCrossRefBubble: vi.fn(),
    } as never;
    const navigation = {
      paletteItems: [],
      runPaletteAction: vi.fn(),
      onToolbarToggleOpen: vi.fn(),
      onToolbarOpenMenu: vi.fn(),
      onToolbarOpenEditor: vi.fn(),
      onToolbarOpenBubble: vi.fn(),
      onToolbarAddChild: vi.fn(),
      onToolbarToggleTaskStatus: vi.fn(),
      onToolbarGoHome: vi.fn(),
      onToolbarGoUp: vi.fn(),
      openSelectedAsStoryLane: vi.fn(),
      showProjectSection: true,
      showNodeSection: true,
      showSimpleBubblesSection: false,
      showBubblesSection: true,
      goPrevProjectPage: vi.fn(),
      goNextProjectPage: vi.fn(),
      openProjectPage: vi.fn(),
      goGrandmotherView: vi.fn(),
      goUpOneView: vi.fn(),
      openSelectedAsMaster: vi.fn(),
      organizeVisibleTree: vi.fn(),
      organizeSelectedBranch: vi.fn(),
      jumpToReferencedNode: vi.fn(),
    } as never;

    const params = buildPlannerWorkspaceBundleParamsFromBundles({
      plannerState,
      selectedNode: null,
      currentRootHasParent: false,
      canvasGraph,
      nodeTypes: {} as never,
      edgeTypes: {},
      nodesById: new Map(),
      childrenByParent: new Map(),
      refs: [],
      derived,
      mutation,
      navigation,
      showSaveErrorToast: false,
      userEmail: "fco@example.com",
      sidebarIsCollapsed: false,
      currentRootKind: "root",
      crossReferencesEnabled: true,
      bubblesSimplifiedMode: true,
      defaultBubbleColor: "#40B6FF",
      canUndo: true,
      canRedo: false,
      undoLabel: "Undo",
      redoLabel: null,
      undo: vi.fn(),
      redo: vi.fn(),
      applyLocalOps: vi.fn(),
      onNodeDoubleClick: vi.fn(),
      openBubblesPanel: vi.fn(),
      openMobileQuickBubble: vi.fn(),
      focusMobileQuickBubbleInput: vi.fn(),
      blurActiveInput: vi.fn(),
    });

    expect(params.canvasSurface.rootNodeId).toBe("root-1");
    expect(params.canvasSurface.onContextAddChild).toBe(mutationHandleContextAddChild);
    expect(params.sidebarMobilePanels.profileName).toBe("FCO");
    expect(params.sidebarMobilePanels.currentRootKind).toBe("root");
    expect(params.sidebarChrome.canUndo).toBe(true);
    expect(params.sidebarChrome.searchMatchCount).toBe(1);
  });
});
